@host = http://localhost:8080


###
POST {{host}}/api/v1/test/parser
Content-Type: application/json

{
  "query": "오늘 현대차 주가 알려줘"
}


###
POST {{host}}/api/v1/test/parser
Content-Type: application/json

{
  "query": "오늘 코스피 지수 알려줘"
}


###
POST {{host}}/api/v1/test/parser
Content-Type: application/json

{
  "query": "투자를 위한 명언 한마디 해줘"
}

###
POST {{host}}/api/v1/test/parser
Content-Type: application/json

{
  "query": "코스피 지수 어때"
}

###
POST {{host}}/api/v1/test/parser
Content-Type: application/json

{
  "query": "내 포트폴리오 수익 종목 알려줘"
}

###
POST {{host}}/api/v1/test/parser
Content-Type: application/json

{
  "query": "오늘 상승률 높은 종목 알려줘"
}
