# Common
server:
  port: 8080

spring:
  application:
    name: aistock
  mvc:
    servlet:
      path: /api/v1 # API versioning
  # Spring AI - OpenAI
  # 실제 키는 환경 변수나 외부 설정 파일을 통해 주입하는 것을 권장합니다.
  # 예: spring.ai.openai.api-key=${OPENAI_API_KEY}
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}  # export SPRING_AI_OPENAI_API_KEY=sk-
      # options:
      #   model: gpt-4-turbo
      #   temperature: 1.0
      #   max-tokens: 2048
      #   top-p: 1.0

# Custom Properties

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.misolab.aistock: debug

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.misolab.aistock: info

